network:
  name: "emier-mainnet"
  version: "1.0.0"
  port: 3030
  max_peers: 1000

consensus:
  beacon_chain_interval: 12
  finality_delay: 2
  max_validators: 1000

sharding:
  total_shards: 64
  shard_size: 1024
  cross_shard_delay: 500

execution:
  parallel_threads: 16
  wasm_timeout: 5
  max_memory: "2GB"

security:
  quantum_resistant: true
  guardian_threshold: 0.67
  self_healing: true

economics:
  base_gas_price: 0.000001
  resource_token_weight: 0.3
  validator_reward: 2.5
